#pragma once
#include <Arduino.h>

const char DASHBOARD_HTML[] PROGMEM = R"rawliteral(
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EdgeGuard ESP32</title><style>
:root{color-scheme:dark;--bg:#0b1020;--panel:#111a2e;--panel2:#17223a;--text:#eef4ff;--muted:#9fb0cc;--ok:#2dd47a;--warn:#ffd166;--bad:#ff5c7a;--accent:#72a7ff;--border:#263653}*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Arial,sans-serif;background:radial-gradient(circle at top left,#1c3763,#0b1020 42%);color:var(--text)}header,main{width:min(1120px,100%);margin:auto;padding:18px}header{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}h1{margin:.1rem 0;font-size:clamp(1.7rem,4vw,2.8rem)}h2{margin:.2rem 0 1rem}.sub,.muted{color:var(--muted)}.pill{display:inline-flex;align-items:center;gap:.4rem;border:1px solid var(--border);background:rgba(17,26,46,.86);border-radius:999px;padding:.45rem .75rem;font-weight:700}.dot{width:.7rem;height:.7rem;border-radius:50%;background:var(--warn)}.online .dot{background:var(--ok)}.offline .dot{background:var(--bad)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px}.card{background:rgba(17,26,46,.92);border:1px solid var(--border);border-radius:18px;padding:16px;box-shadow:0 18px 45px rgba(0,0,0,.24)}.label{color:var(--muted);font-size:.9rem}.value{font-size:1.8rem;font-weight:800;margin-top:.3rem;overflow-wrap:anywhere}.badge{display:inline-block;border-radius:999px;padding:.35rem .65rem;background:var(--panel2);border:1px solid var(--border);font-weight:800}.badge.ok{color:var(--ok)}.badge.warn{color:var(--warn)}.badge.bad{color:var(--bad)}.controls{display:flex;flex-wrap:wrap;gap:10px}button{min-height:44px;border:1px solid var(--border);border-radius:12px;background:#203458;color:var(--text);font-weight:800;padding:.75rem 1rem;cursor:pointer}button:hover,button.active{background:var(--accent);color:#061020}button:disabled{opacity:.55;cursor:wait}pre{min-height:160px;max-height:280px;overflow:auto;white-space:pre-wrap;background:#070b14;border-radius:14px;padding:14px;color:#dbe7ff}.wide{grid-column:1/-1}.fault{border-left:5px solid var(--ok)}.fault.alert{border-left-color:var(--warn)}.fault.bad{border-left-color:var(--bad)}@media(max-width:650px){header{display:block}.value{font-size:1.45rem}}
</style></head><body><header><div><h1>EdgeGuard ESP32</h1><div class="sub">Local smart-room monitor and low-voltage relay controller</div></div><div id="conn" class="pill"><span class="dot"></span><span id="connText">Loading</span></div></header><main><section class="grid"><article class="card"><div class="label">Mode</div><div id="mode" class="value badge">--</div></article><article class="card"><div class="label">State</div><div id="state" class="value badge">--</div></article><article class="card"><div class="label">Temperature</div><div id="temp" class="value">--</div></article><article class="card"><div class="label">Humidity</div><div id="hum" class="value">--</div></article><article class="card"><div class="label">Distance</div><div id="dist" class="value">--</div></article><article class="card"><div class="label">Light</div><div id="light" class="value">--</div></article><article class="card"><div class="label">Occupancy</div><div id="occ" class="value">--</div></article><article class="card"><div class="label">Relays</div><div id="relays" class="value">--</div></article><article class="card wide"><h2>Controls</h2><div class="controls"><button data-mode="AUTO" onclick="act('/api/mode/auto',this)">AUTO Mode</button><button data-mode="MANUAL" onclick="act('/api/mode/manual',this)">MANUAL Mode</button><button data-mode="AWAY" onclick="act('/api/mode/away',this)">AWAY Mode</button><button onclick="act('/api/relay1/on',this)">Relay 1 ON</button><button onclick="act('/api/relay1/off',this)">Relay 1 OFF</button><button onclick="act('/api/relay2/on',this)">Relay 2 ON</button><button onclick="act('/api/relay2/off',this)">Relay 2 OFF</button></div><p id="action" class="muted">Ready.</p></article><article id="faultCard" class="card wide fault"><h2>Fault / Alert</h2><div id="fault">No fault</div></article><article class="card wide"><h2>Device</h2><div id="device" class="muted">--</div></article><article class="card wide"><h2>Event Log</h2><pre id="logs">Loading...</pre></article></section></main><script>
const $=id=>document.getElementById(id);const yn=v=>v?'YES':'NO', on=v=>v?'ON':'OFF';let busy=false;
async function act(path,btn){if(busy)return;busy=true;btn.disabled=true;$('action').textContent='Sending '+path+' ...';try{const r=await fetch(path,{method:'POST'});if(!r.ok)throw Error(r.status);$('action').textContent='Command accepted.';await refresh();}catch(e){$('action').textContent='Command failed: '+e.message;}finally{btn.disabled=false;busy=false;}}
function badge(el,val){el.textContent=val;el.className='value badge '+(val==='FAULT'?'bad':val==='ALERT'||val==='AWAY'?'warn':'ok')}
async function refresh(){try{const [sr,lr]=await Promise.all([fetch('/api/status',{cache:'no-store'}),fetch('/api/logs',{cache:'no-store'})]);if(!sr.ok||!lr.ok)throw Error('HTTP '+sr.status+'/'+lr.status);const s=await sr.json(), logs=await lr.json();$('conn').className='pill online';$('connText').textContent='Online';badge($('mode'),s.mode);badge($('state'),s.state);$('temp').textContent=s.temperature_c===null?'DHT ERROR':s.temperature_c.toFixed? s.temperature_c.toFixed(1)+' °C':s.temperature_c+' °C';$('hum').textContent=s.humidity===null?'DHT ERROR':s.humidity+' %';$('dist').textContent=s.distance_cm===null?'NO ECHO':s.distance_cm+' cm';$('light').textContent=s.light_is_dark?'DARK':'BRIGHT';$('occ').textContent=yn(s.occupied);$('relays').textContent='R1 '+on(s.relay1)+' / R2 '+on(s.relay2);$('fault').textContent=s.fault_reason&&s.fault_reason.length?s.fault_reason:(s.temperature_alert?'Temperature alert active':'No fault');$('faultCard').className='card wide fault '+(s.state==='FAULT'?'bad':(s.state==='ALERT'?'alert':''));$('device').textContent='Uptime '+(s.uptime_s||0)+'s · Wi-Fi '+(s.wifi_mode||'--')+' · IP '+(s.ip||'--')+' · Heap '+(s.heap_free||'--')+' bytes'+(s.rssi?' · RSSI '+s.rssi+' dBm':'');$('logs').textContent=logs.length?logs.join('\n'):'No events yet.';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===s.mode));}catch(e){$('conn').className='pill offline';$('connText').textContent='Offline';$('logs').textContent='Unable to refresh dashboard: '+e.message;}}
setInterval(refresh,2000);refresh();
</script></body></html>
)rawliteral";
